export {default as App} from './app/app.component'
export {default as Login} from './login/login.component'
export {default as Register} from './register/register.component'
export {default as Dashboard} from './dashboard/dashboard.component'
export {default as History} from './history/history.component'
export {default as Account} from './account/account.component'